import { getCookie } from 'cookies-next'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <a href="/api/google">Login with google</a>

        </main>
 
    </div>
  )
}

export async function getServerSideProps({ req, res }) {
  try {
    const cookieExists = getCookie('token', {req, res });
    if(cookieExists) return { redirect: { destination: 'http://localhost:3000/dashboard' } }
    else return { props: { }};
  } catch (error) {
    return { props: { }};
  }
}
export default Home
