import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { connectToDatabase } from '../middleware/database'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        </main>
 
    </div>
  )
}

export async function getServerSideProps(params: any) {
  const {db} = await connectToDatabase();

  return {
    props: {
     
    }
  }
  
  
}
export default Home
